site_name: MonitoraEA

theme:
  name: material

nav:
  - Início (Versão Dez/2025): index.md
  - Arquitetura (Versão Dez/2025): arquitetura.md
  - Módulos (Versão Dez/2025): modulos.md
  - Fluxos (Versão Dez/2025): fluxos.md
  - Governança (Versão Dez/2025): governanca.md
  - Maturidade Tecnológica (Versão Dez/2025): maturidade.md
  - API: api.md
  - Banco de Dados: banco.md
  - Troubleshooting: troubleshooting.md
  - Resultados (Versão Dez/2025): resultados.md
  - Roadmap (Versão Dez/2025): roadmap.md
  - Plano de Transferência (Versão Dez/2025): transferencia.md
  - Questões Legais (Versão Dez/2025): questoeslegais.md
  - Considerações Finais (Versão Dez/2025): consideracoes.md
  - Como Contribuir (versão Mai/2026): contribuicao.md

markdown_extensions:
  - footnotes
