site_name: MonitoraEA

theme:
  name: material

nav:
  - Início: index.md
  - Arquitetura: arquitetura.md
  - Módulos: modulos.md
  - API: api.md
  - Banco de Dados: banco.md
  - Troubleshooting: troubleshooting.md
